ALTER TABLE job_tasks ADD COLUMN IF NOT EXISTS machine_used VARCHAR(100);
ALTER TABLE job_tasks ADD COLUMN IF NOT EXISTS start_time TIMESTAMP;
ALTER TABLE job_tasks ADD COLUMN IF NOT EXISTS end_time TIMESTAMP;
ALTER TABLE job_tasks ADD COLUMN IF NOT EXISTS material_consumption VARCHAR(500);
ALTER TABLE job_tasks ADD COLUMN IF NOT EXISTS wastage VARCHAR(200);
ALTER TABLE job_tasks ADD COLUMN IF NOT EXISTS remarks TEXT;
